Onder lesson32 js
frontend-from-0/240123-exercises pull request #126
Opened 2023-11-24 09:02 UTC by ondermartin

2023-11-27 21:26 UTC, annasvst requested changes
Hi Önder, this is a very good start! Now RecipeDetail component is missing in your code. I see that there's a file in components folder created for it but it's empty. You need to add code to present recipe details. Some elements like div, heading, a couple of paragraphs and image is enough to display recipe data. Also, add back button in the Recipe details component and pass the 'handleClearSelection' to it to return to the main page.

2023-12-15 21:52 UTC, annasvst commented on JS/Lesson32/onder/my-app/src/App.jsx
>  import {SearchBar} from './components/SearchBar';
This import is missing:
import { RecipeDetail } from './components/RecipeDetail';

2023-12-15 21:52 UTC, annasvst commented on JS/Lesson32/onder/my-app/src/components/RecipeDetail/index.jsx
> +const RecipeDetail = ({ recipe, onClearSelection }) => {
Must have: export the RecipeDetail component
```suggestion
export const RecipeDetail = ({ recipe, onClearSelection }) => {
```

2023-12-15 21:52 UTC, annasvst commented on JS/Lesson32/onder/my-app/src/components/RecipeDetail/index.jsx
> +      <p>{recipe.strMeal}</p>
Nice to have: add more details about the recipe:

```
  <div class="recipe-details-container">
      <h2 class="heading">Recipe Details</h2>
      <div class="image-content">
        <img class="recipe-thumbnail" src={recipe.strMealThumb} alt={recipe.strMeal} />
      </div>
      <div class="text-content">
        <p>{recipe.strMeal}</p>
        <p>{recipe.strInstructions}</p>
        <button onClick={onClearSelection}>Go Back to Recipes</button>
      </div>
```

2023-12-15 21:52 UTC, annasvst commented on JS/Lesson32/onder/my-app/src/components/RecipeDetail/index.jsx
> +
NIce to have: add styles to style the page nicely:

```suggestion
import './styles.css';
```

CSS code:
```
.recipe-details-container {
  display: grid;
  grid-template-rows: 50px 1fr;
  grid-template-columns: 1fr 1fr;
  grid-template-areas: "heading heading"
  "image-content text-content";
  gap: 20px;
}

.heading {
  grid-area: heading;
}

.image-content {
  grid-area: image-content;
}

.text-content {
  grid-area: text-content;
}

.recipe-thumbnail {
  width: 100%;
}
```

2023-12-18 11:08 UTC, annasvst requested changes
Hi Onur, you have code in App.js before that would set selected recipe when the user clicks on the recipe from the list. The code was removed in this commit: https://github.com/frontend-from-0/240123-exercises/pull/126/commits/2093d507b011fa30dcd2e0e359a3f0bd399b4706

Please re-add the missing part from the mentioned commit and re-submit

2023-12-18 15:53 UTC, ondermartin commented
Hello Anna 
I have messed it up so much but hopefully this will fixed it I got so confused. HAHAHAHA

2023-12-18 21:50 UTC, annasvst approved these changes
Works now, approved!

2024-01-22 08:44 UTC, merged